ingress-nginx:
  controller:
    service:
      type: LoadBalancer
      # For k3d, mapped by hostPorts via k3d CLI/Makefile

postgresql:
  enabled: true
  auth:
    username: cbb
    password: cbbpass
    database: cbb_upsets
  image:
    repository: bitnami/postgresql
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  primary:
    persistence:
      enabled: true
  test:
    enabled: false
