apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cbb-upsets.nginxFullname" . }}
  labels:
    {{- include "cbb-upsets.nginxLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      {{- include "cbb-upsets.nginxSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cbb-upsets.nginxSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.nginx.service.port }}
          {{- with .Values.nginx.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
