{{- $root := . -}}
{{- with $root.Values.runtime.secretEnv }}
{{- $secretEnv := . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cbb-upsets.runtimeSecretFullname" $root }}
  labels:
    {{- include "cbb-upsets.runtimeLabels" $root | nindent 4 }}
type: Opaque
stringData:
  {{- range $name := keys $secretEnv | sortAlpha }}
  {{ $name }}: {{ index $secretEnv $name | quote }}
  {{- end }}
{{- end }}
