apiVersion: v1
kind: Service
metadata:
  name: {{ include "cbb-upsets.nginxFullname" . }}
  labels:
    {{- include "cbb-upsets.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.nginx.service.type "NodePort" }}
      nodePort: {{ .Values.nginx.service.nodePort }}
      {{- end }}
  selector:
    {{- include "cbb-upsets.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
